name: MSBuild

on: [push]

env:
  DUMMY: a

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild mupen64.sln -t:rebuild -property:Configuration=Release

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: mupen-artifact
        path: build/mupen64-x86.exe
        retention-days: 14
