name: MSBuild

on: [push]

env:
  DUMMY: a

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Visual Studio 2022 Preview
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\Installer"
        .\vs_installer.exe modify --channelId VisualStudio.17.Preview

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild winproject/mupen64.sln -t:rebuild -verbosity:diag -property:Configuration=Release
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: mupen-artifact
        path: winproject/bin/mupen64.exe
        retention-days: 7
