name: test-clang-format

on: [ push ]

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.18.2
        with:
          source: './src'
          exclude: './lib ./tools'
          extensions: 'h,cpp'
          clangFormatVersion: 18.1.8
          style: file
